#!/usr/bin/env bash

#Check Privileges
if [ $(whoami) != 'root' ]; then
  echo "Please run with sudo privileges"
  exit 0
else

#Uninstall snapd
cd /etc/apt/preferences.d/
cat > nosnap.pref <<EOF
# To prevent repository packages from triggering the installation of snap,
# this file forbids snapd from being installed by APT.

Package: snapd
Pin: release a=*
Pin-Priority: -10
EOF
cd ..
snap remove --purge $(snap list | awk '!/^Name|^core/ {print $1}')
systemctl stop snapd
systemctl disable snapd
apt purge -y snapd gnome-software-plugin-snap
rm -rf ~/snap/
rm -rf /var/cache/snapd/

#Install Flatpak
# Latest flatpak package is available on Ubuntu 22.04, if used on older Versions uncomment the PPA
#add-apt-repository ppa:alexlarsson/flatpak
apt update
apt install -y flatpak gnome-software-plugin-flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi
