name: Unittest Ubuntu-18.04

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@main

      - name: Run script
        run: |
          sudo bash flatpatch

